development:  
  :concurrency: 5
  :logfile: ./log/sidekiq_development.log
  :pidfile: tmp/pids/sidekiq.pid
production:  
  :concurrency: 5
  :logfile: ./log/sidekiq_development.log
  :pidfile: tmp/pids/sidekiq.pid
:queues:
  - default
  - playlists
