development:
  facebook_key: '1668283266746588'
  facebook_secret: 'f910988d26d91da102ff31d046fcc358'
  google_client_id: '975957271354-jdtgv973h1b1sm73sqtuhedcuqimi36b.apps.googleusercontent.com'
  google_client_secret: '4uBVlJjNtcYdAq7XTA7apoxj'
  youtube_api_key: 'AIzaSyDCAryHPLofEdKUeFB27y2ngocVRMJ252s'
  websocket_url: 'localhost:3000/websocket'

production:
  facebook_key: '1668283266746588'
  facebook_secret: 'f910988d26d91da102ff31d046fcc358'
  google_client_id: '975957271354-jdtgv973h1b1sm73sqtuhedcuqimi36b.apps.googleusercontent.com'
  google_client_secret: '4uBVlJjNtcYdAq7XTA7apoxj'
  youtube_api_key: 'AIzaSyDCAryHPLofEdKUeFB27y2ngocVRMJ252s'
  websocket_url: 'youtubetonight.herokuapp.com/websocket'
