development:
  facebook_key: '1668283266746588'
  facebook_secret: 'f910988d26d91da102ff31d046fcc358'
  youtube_api_key: 'AIzaSyDCAryHPLofEdKUeFB27y2ngocVRMJ252s'
  websocket_url: 'localhost:3000/websocket'

production:
  facebook_key: '1668283266746588'
  facebook_secret: 'f910988d26d91da102ff31d046fcc358'
  youtube_api_key: 'AIzaSyDCAryHPLofEdKUeFB27y2ngocVRMJ252s'
  websocket_url: 'youtubetonight.herokuapp.com/websocket'
